# -*- coding: utf-8 -*-
"""Train model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19BgwMcIFlAFwixNbfjJEIqKDdSU7uyvA
"""

import pandas as pd

# df.to_csv("eth_gas_clean_1min.csv", index=False)
df = pd.read_csv("eth_gas_clean_1min.csv")

import numpy as np

df = df.replace([np.inf, -np.inf], np.nan).dropna()

df = df[(df['avg_gas_price_gwei'] < df['avg_gas_price_gwei'].quantile(0.99)) &
        (df['avg_gas_price_gwei'] > df['avg_gas_price_gwei'].quantile(0.01))]

# Log-transform để giảm độ lệch của biến mục tiêu
df['target_log'] = np.log1p(df['avg_gas_price_gwei'])

for lag in [1, 2, 3, 5, 10]:
    df[f'gas_t-{lag}'] = df['avg_gas_price_gwei'].shift(lag)

df['gas_rolling_5'] = df['avg_gas_price_gwei'].rolling(window=5).mean()
df['gas_rolling_30'] = df['avg_gas_price_gwei'].rolling(window=30).mean()

df = df.dropna().reset_index(drop=True)

df

df.to_csv("eth_gas_1min_final.csv", index=False)

"""Ridge"""

import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

features = [
    'gas_t-1', 'gas_t-2', 'gas_t-3', 'gas_t-5', 'gas_t-10',
    'gas_rolling_5', 'gas_rolling_30',
    'tx_count', 'total_gas_used', 'avg_block_full_ratio'
]
target = 'avg_gas_price_gwei'

X = df[features].values
y = df[target].values

split_index = int(len(df) * 0.8)
X_train, X_test = X[:split_index], X[split_index:]
y_train, y_test = y[:split_index], y[split_index:]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ridge = Ridge(alpha=1.0, random_state=42)
ridge.fit(X_train_scaled, y_train)

y_train_pred = ridge.predict(X_train_scaled)
y_test_pred = ridge.predict(X_test_scaled)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

mae_train = mean_absolute_error(y_train, y_train_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)

rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))

print(f"Train: R² = {r2_train:.3f}, MAE = {mae_train:.3f}, RMSE = {rmse_train:.3f}")
print(f"Test : R² = {r2_test:.3f}, MAE = {mae_test:.3f}, RMSE = {rmse_test:.3f}")





"""XGBoost"""

from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

features = [
    'gas_t-1', 'gas_t-2', 'gas_t-3', 'gas_t-5', 'gas_t-10',
    'gas_rolling_5', 'gas_rolling_30',
    'tx_count', 'total_gas_used', 'avg_block_full_ratio'
]
target = 'avg_gas_price_gwei'

X = df[features].values
y = df[target].values

split_index = int(len(df) * 0.8)
X_train, X_test = X[:split_index], X[split_index:]
y_train, y_test = y[:split_index], y[split_index:]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

xgb = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    objective='reg:squarederror',
    n_jobs=-1,
    eval_metric='rmse'
)

xgb.fit(
    X_train_scaled, y_train,
    eval_set=[(X_train_scaled, y_train), (X_test_scaled, y_test)],
    verbose=False
)

y_train_pred = xgb.predict(X_train_scaled)
y_test_pred = xgb.predict(X_test_scaled)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

mae_train = mean_absolute_error(y_train, y_train_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)

rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))

print(f"Train -> R² = {r2_train:.3f}, MAE = {mae_train:.3f}, RMSE = {rmse_train:.3f}")
print(f"Test  -> R² = {r2_test:.3f}, MAE = {mae_test:.3f}, RMSE = {rmse_test:.3f}")





"""GRU"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

features = [
    'gas_t-1', 'gas_t-2', 'gas_t-3', 'gas_t-5', 'gas_t-10',
    'gas_rolling_5', 'gas_rolling_30',
    'tx_count', 'total_gas_used', 'avg_block_full_ratio'
]
target = 'avg_gas_price_gwei'

X = df[features].values
y = df[target].values

split_index = int(len(df) * 0.8)
X_train, X_test = X[:split_index], X[split_index:]
y_train, y_test = y[:split_index], y[split_index:]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

def create_sequences(X, y, window=30):
    Xs, ys = [], []
    for i in range(window, len(X)):
        Xs.append(X[i-window:i])
        ys.append(y[i])
    return np.array(Xs), np.array(ys)

WINDOW = 5
X_train_seq, y_train_seq = create_sequences(X_train_scaled, y_train, WINDOW)
X_test_seq, y_test_seq = create_sequences(X_test_scaled, y_test, WINDOW)

print(f"Train shape: {X_train_seq.shape}, Test shape: {X_test_seq.shape}")

model = Sequential([
    GRU(128, return_sequences=True, input_shape=(X_train_seq.shape[1], X_train_seq.shape[2])),
    Dropout(0.2),
    GRU(64),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = model.fit(
    X_train_seq, y_train_seq,
    validation_split=0.1,
    epochs=30,
    batch_size=128,
    callbacks=[early_stop],
    verbose=1
)

y_train_pred = model.predict(X_train_seq).flatten()
y_test_pred = model.predict(X_test_seq).flatten()

r2_train = r2_score(y_train_seq, y_train_pred)
r2_test = r2_score(y_test_seq, y_test_pred)

mae_train = mean_absolute_error(y_train_seq, y_train_pred)
mae_test = mean_absolute_error(y_test_seq, y_test_pred)

rmse_train = np.sqrt(mean_squared_error(y_train_seq, y_train_pred))
rmse_test = np.sqrt(mean_squared_error(y_test_seq, y_test_pred))

print(f"Train -> R² = {r2_train:.3f}, MAE = {mae_train:.3f}, RMSE = {rmse_train:.3f}")
print(f"Test  -> R² = {r2_test:.3f}, MAE = {mae_test:.3f}, RMSE = {rmse_test:.3f}")









